# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

permalink: /:year/:month/:title 

# Site settings
title: Vinh's Blog
email: luuthevinh7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Xin chào, mình tên là Lưu Thế Vinh. Mình thích Lập trình, làm Game và cũng tập tành Thiết kế mấy thứ linh tinh.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://luuthevinh.me" # the base hostname & protocol for your site
twitter_username: thevinh14
github_username:  luuthevinh
facebook_username: eric14
instagram_username: _vinh14
blog_avatar: /assets/images/vinh-ava-300.png

# Build settings
markdown: kramdown

gems: 
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vinh"
      comments: yes

facebook:
  app_id: 1021504654629283
  publisher: 100001840703474
  admins: 100001840703474